import DataTable from "../components/DataTable";
import PageHeader from "../components/PageHeader";
import { reports } from "../data/mockData";

const columns = ["Report ID", "Report Name", "Generated By", "Generated At", "Format"];

export default function ReportsPage() {
  return (
    <section>
      <PageHeader
        title="Reports"
        subtitle="Generate executive-ready views for goal attainment, alignment, and performance trends."
        actions={<button className="button-primary">Generate Report</button>}
      />
      <DataTable
        columns={columns}
        rows={reports}
        renderCell={(row) => (
          <>
            <td className="px-4 py-3 text-slate-100">{row.id}</td>
            <td className="px-4 py-3 text-slate-200">{row.name}</td>
            <td className="px-4 py-3 text-slate-300">{row.generatedBy}</td>
            <td className="px-4 py-3 text-slate-300">{row.generatedAt}</td>
            <td className="px-4 py-3 text-slate-300">{row.format}</td>
          </>
        )}
      />
    </section>
  );
}
